name: Run Beating_heart Script

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có code mới được đẩy lên nhánh `main`

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code 
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Create environment Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Set xvfb
      - name: Install dependencies for tkinter
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      # 4. Run Xvfb 
      - name: Run Beating_heart with Xvfb
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python Beating_heart.py
